# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, bootstrap, bootstrap-responsive, datepicker]

  javascripts:    [jquery-1.7.2.min.js, bootstrap.min.js, bootstrap-alert, bootstrap-button, bootstrap-carousel, bootstrap-collapse, bootstrap-datepicker, bootstrap-dropdown, bootstrap-modal, bootstrap-popover, bootstrap-scrollspy, bootstrap-tab, bootstrap-tooltip, bootstrap-transition, bootstrap-typeahead, ]

  has_layout:     true
  layout:         layout
